<?php

return [
    'home' => [
        'hero' => [
            'hero.visible',
            'hero.tagline',
            'hero.heading',
            'hero.description',
            'hero.button_label',
            'hero.button_link',
            'hero.image',
            'hero.slides',
            'hero.highlights',
        ],
        'about' => [
            'about.visible',
            'about.heading',
            'about.text_primary',
            'about.text_secondary',
            'about.badge_text',
            'about.image_primary',
            'about.image_secondary',
            'about.checklist',
        ],
        'features' => [
            'features.visible',
            'features.heading',
            'features.items',
        ],
        'projects' => [
            'projects.visible',
            'projects.heading',
            'projects.subheading',
            'projects.items',
        ],
        'products' => [
            'products.visible',
            'products.heading',
        ],
        'services' => [
            'services.visible',
            'services.heading',
            'services.description',
            'services.description_secondary',
            'services.phone',
            'services.phone_label',
            'services.items',
        ],
        'team' => [
            'team.visible',
            'team.heading',
            'team.description',
            'team.members',
        ],
        'testimonials' => [
            'testimonials.visible',
            'testimonials.items',
        ],
        'newsletter' => [
            'newsletter.visible',
            'newsletter.heading',
            'newsletter.description',
            'newsletter.placeholder',
            'newsletter.image',
        ],
        'contact' => [
            'contact.visible',
            'contact.heading',
            'contact.map',
        ],
    ],
    'contact' => [
        'hero' => [
            'hero.visible',
            'hero.mask',
            'hero.background',
            'hero.heading',
            'hero.description',
        ],
        'details' => [
            'details.visible',
            'details.heading',
            'details.description',
            'details.items',
        ],
        'social' => [
            'social.visible',
            'social.heading',
            'social.description',
            'social.items',
        ],
        'map' => [
            'map.visible',
            'map.heading',
            'map.embed',
        ],
    ],
    'product' => [
        'hero' => [
            'hero.visible',
            'hero.mask',
            'hero.image',
            'title',
            'hero.description',
        ],
        'filters' => [
            'filters.search_label',
            'filters.search_placeholder',
            'filters.category_label',
            'filters.category_all_label',
            'filters.sort_label',
            'filters.sort_default_label',
            'filters.sort_price_low_label',
            'filters.sort_price_high_label',
            'filters.sort_popular_label',
            'filters.apply_label',
            'filters.reset_label',
        ],
        'grid' => [
            'grid.button_label',
            'grid.empty_text',
        ],
    ],
    'product-detail' => [
        'hero' => [
            'hero.visible',
            'hero.mask',
            'hero.image',
            'hero.title',
            'hero.description',
        ],
        'details' => [
            'details.quantity_label',
            'details.add_to_cart_label',
            'details.added_feedback',
            'details.error_feedback',
        ],
        'comments' => [
            'comments.visible',
            'comments.heading',
            'comments.empty_text',
        ],
        'recommendations' => [
            'recommendations.visible',
            'recommendations.heading',
            'recommendations.button_label',
            'recommendations.empty_text',
        ],
    ],
    'article' => [
        'hero' => [
            'hero.visible',
            'hero.mask',
            'hero.image',
            'hero.heading',
            'hero.description',
            'search.placeholder',
        ],
        'list' => [
            'list.button_label',
            'list.empty_text',
            'articles.items',
        ],
        'timeline' => [
            'timeline.visible',
            'timeline.heading',
        ],
    ],
    'article-detail' => [
        'hero' => [
            'hero.visible',
            'hero.mask',
            'hero.image',
            'hero.title',
        ],
        'meta' => [
            'meta.show_author',
            'meta.show_date',
        ],
        'comments' => [
            'comments.visible',
            'comments.heading',
            'comments.disabled_text',
        ],
        'recommendations' => [
            'recommendations.visible',
            'recommendations.heading',
        ],
    ],
    'shipping' => [
        'form' => [
            'form.heading',
            'form.button_label',
        ],
        'methods' => [
            'methods.heading',
            'methods.fetch_label',
        ],
        'summary' => [
            'summary.heading',
            'summary.note',
        ],
    ],
    'gallery' => [
        'hero' => [
            'hero.visible',
            'hero.mask',
            'hero.background',
            'hero.heading',
            'hero.description',
        ],
        'filters' => [
            'filters.visible',
            'filters.heading',
            'filters.all_label',
        ],
        'grid' => [
            'grid.heading',
            'grid.empty_text',
        ],
    ],
    'about' => [
        'hero' => [
            'hero.visible',
            'hero.background',
            'hero.heading',
            'hero.breadcrumb',
        ],
        'intro' => [
            'intro.visible',
            'intro.heading',
            'intro.description_primary',
            'intro.description_secondary',
            'intro.badge_text',
            'intro.image_primary',
            'intro.image_secondary',
            'intro.checklist',
            'intro.button_label',
            'intro.button_link',
            'intro.social_links',
        ],
        'quote' => [
            'quote.visible',
            'quote.text',
            'quote.author',
        ],
        'team' => [
            'team.visible',
            'team.heading',
            'team.description',
            'team.members',
        ],
        'advantages' => [
            'advantages.visible',
            'advantages.heading',
            'advantages.description',
            'advantages.items',
        ],
    ],
    'cart' => [
        'header' => [
            'title',
            'subtitle',
        ],
        'empty' => [
            'empty.message',
            'empty.button',
        ],
        'actions' => [
            'button.shipping',
            'button.payment',
        ],
    ],
    'order' => [
        'hero' => [
            'hero.visible',
            'hero.mask',
            'hero.background',
            'hero.heading',
            'hero.description',
        ],
        'empty' => [
            'empty.title',
            'empty.description',
            'empty.button',
        ],
    ],
    'layout' => [
        'navigation' => [
            'navigation.brand.visible',
            'navigation.brand.text',
            'navigation.brand.logo',
            'navigation.brand.icon',
            'navigation.link.home',
            'navigation.link.about',
            'navigation.link.products',
            'navigation.link.gallery',
            'navigation.link.contact',
            'navigation.link.articles',
            'navigation.link.article-detail',
            'navigation.link.orders',
            'navigation.icon.cart',
            'navigation.button.login',
        ],
        'footer' => [
            'footer.hotlinks.visible',
            'footer.address.visible',
            'footer.address.text',
            'footer.phone.visible',
            'footer.phone.text',
            'footer.email.visible',
            'footer.email.text',
            'footer.social.visible',
            'footer.social.text',
            'footer.schedule.visible',
            'footer.schedule.text',
            'footer.copyright',
        ],
        'floating' => [
            'floating.visible',
            'floating.buttons',
        ],
    ],
];
